main() {
  const a = 2;
  const b = 5;
  dynamic c = 3;
  print("Arithmtic operators");
  print(a + b);
  print(a - b);
  print(a * b);
  print(a / b);
  print(a ~/ b);
  print(c++);
  print(c--);
  print("Relational Operators");
  print(a > b);
  print(a < b);
  print(a == b);
  print(a != b);
  print(a <= b);
  print(a >= b);
  print("Logic Operators");
  print(a == 5 && b == 2);
  print(a == 5 || b == 5);
  print(!(a == 7));
  print("Bitwise Operators");
  print(a & b);
  print(a | b);
  print(~a);
  print(a ^ b);
  print(b << 2);
  print(b >> 2);
  print("Equality Operators");
  c += 2;
  print(c);
  c -= 2;
  print(c);
  c *= 2;
  print(c);
  c /= 2;
  print(c);
}
